name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Checkout config files
        uses: actions/checkout@v2
        with:
          ref: eslint-config
          path: config

      - name: Check md5
        run: md5sum .github/workflows/ci.yml

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Check ESLint rules
        run: npx eslint --no-inline-config --config ./config/.eslintrc.json ./src

      - name: Check if TypeScript compiles
        run: npx tsc --noEmit --project ./config
